INSERT INTO CHILD (CHILD_VALUE) VALUES ('CHILD-A');
INSERT INTO CHILD (CHILD_VALUE) VALUES ('CHILD-B');
INSERT INTO CHILD (CHILD_VALUE) VALUES ('CHILD-C');
INSERT INTO CHILD (CHILD_VALUE) VALUES ('CHILD-D');
INSERT INTO CHILD (CHILD_VALUE) VALUES ('CHILD-E');

INSERT INTO PARENT (PARENT_VALUE, FK_CHILD_ID) VALUES ('PARENT-A', 1);
INSERT INTO PARENT (PARENT_VALUE, FK_CHILD_ID) VALUES ('PARENT-B', 2);
INSERT INTO PARENT (PARENT_VALUE, FK_CHILD_ID) VALUES ('PARENT-C', 3);
INSERT INTO PARENT (PARENT_VALUE, FK_CHILD_ID) VALUES ('PARENT-D', 2);
INSERT INTO PARENT (PARENT_VALUE, FK_CHILD_ID) VALUES ('PARENT-E', 1);